name: first Workflow
on: workflow_disptach
jobs: 
  first-job:
    runs-on: ubantu-latest
    steps:
      - name: Greetings
        run: echo "Hello github world!"
      - name: GoodByeForNow
        run: echo "We will meet soon - Good by till then!!!"
      
    
